kind: Template
apiVersion: v1
metadata:
  name: calculadora-front
  description: "Template to deploy Piloto #3 Frontend"
  tags: ibmcom/ace
labels:
  template: calculadora-front
  version: "1.0"
  app: ${APP}
parameters:
  - description: Application deployment name
    displayName: Application
    required: true
    name: APP
    value: 'calculadora'
  - description: 'The base name assigned to all of the objects defined in this template.'
    displayName: Name
    required: true
    name: NAME
    value: front
  - description: The OpenShift Namespace where the ImageStream resides.
    displayName: Namespace
    name: NAMESPACE
    required: true
    value: piloto3
  - description: The ImageStream name
    displayName: ImageStream
    name: IMAGE
    required: true
    value: front
  - description: Service Account with ibm-anyuid-scc configured
    displayName: Service Account 
    name: SA
    required: true
    value: default
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APP}-${NAME}
    spec:
      replicas: 1
      selector:
        template: calculadora-front
        version: "1.0"
        app: ${APP}
      template:
        metadata:
          labels:
            template: calculadora-front
            version: "1.0"
            app: ${APP}
        spec:
          serviceAccount: ${SA}
          containers:
            - name: springboot
              image: " "
              imagePullPolicy: "Always"
              args:
                - "--com.gbm.url=http://${APP}-api:7800/calculadora/v1/operaciones"
              ports:
                - containerPort: 8080
                  protocol: TCP
                  name: http
              livenessProbe:
                httpGet:
                  path: /
                  port: http
              readinessProbe:
                httpGet:
                  path: /
                  port: http
      triggers:
        - type: ImageChange
          imageChangeParams:
            containerNames:
              - springboot
            automatic: true
            from:
              kind: ImageStreamTag
              name: ${IMAGE}:latest
              namespace: ${NAMESPACE}
        - type: ConfigChange
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APP}-${NAME}
    labels:
      app: ${APP}
    spec:
      selector:
        template: calculadora-front
        version: "1.0"
        app: ${APP}
      type: ClusterIP
      ports:
        - port: 8080
          protocol: TCP
          name: 8080-tcp